language: lisp

sudo: required

#dist: trusty

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl

# matrix:
#   allow_failures:
#     - env: LISP=ccl32

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - mkdir -p ~/.roswell/lisp/quicklisp/dists/pauldist
  - curl -L http://pauldist.kisp.in/pauldist.txt > ~/.roswell/lisp/quicklisp/dists/pauldist/distinfo.txt
  - touch  ~/.roswell/lisp/quicklisp/dists/pauldist/enabled.txt
  - ros -e '(format t "~A ~A~%" (lisp-implementation-type) (lisp-implementation-version))'

script:
  - ros -s simple-csp-solver-test -e '(uiop:quit (if (myam:load-and-run! "simple-csp-solver-test") 0 1))'
